kind: DataSetConfiguration
apiVersion: client.uor-framework.io/v1alpha1
linkedCollections:
  - 100.115.92.198:5001/models:latest
files:
  - file: "*.pkl"
    attributes:
      type: model
  - file: model1.pkl
    attributes:
      size: small
  - file: model2.pkl
    attributes:
      size: medium
  - file: model3.pkl
    attributes:
      size: large